name: Only tests

on:
  push:
    branch-ignore:
      - main
      - master
  pull_request:
    branch-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distributed: adopt

      - name: Setup Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 3.8.2

      - name: All the Tests and Coverage Checks
        run: mvn clean install